[petfinder_api]
api_url = "https://api.petfinder.com/v2/"
token_url = "https://api.petfinder.com/v2/oauth2/token"
api_key = "your API key here"
secret_key = "your secret key here"
api_connection_retries = 3
api_connection_retry_delay = 1

[fred_api]
api_url = "https://api.stlouisfed.org/fred/"
api_key = "your API key here"
api_connection_retries = 3
api_connection_retry_delay = 1

[aws_s3]
bucket_name = "your bucket name here"
bucket_key = "your bucket key here"

