[fred_api]
api_url = "https://api.stlouisfed.org/fred/"
api_key = ""
api_connection_retries = 10
api_connection_retry_delay = 5

[petfinder_api]
api_url = "https://api.petfinder.com/v2/"
token_url = "https://api.petfinder.com/v2/oauth2/token"
api_key = ""
secret_key = ""
api_connection_retries = 10
api_connection_retry_delay = 5