[fred_api]
api_url = "https://api.stlouisfed.org/fred/"
api_key = ""
[petfinder_api]
api_url = "https://api.petfinder.com/v2/"
token_url = "https://api.petfinder.com/v2/oauth2/token"
api_key = ""
api_secret_key = ""