[petfinder_api]
api_url = "https://api.petfinder.com/v2/"
token_url = "https://api.petfinder.com/v2/oauth2/token"
api_key = "your API key here"
secret_key = "your secret key here"

[econ_api]
api_url = "https://newsapi.org/v2/"
api_key = "your API key here"

[aws_s3]
bucket_name = "your bucket name here"
bucket_key = "your bucket key here"

