[petfinder_api]
num-tries_less_than_max = "Petfinder API get_access_token failed on retry {num_retries} with status code: \
{response.status_code} and details: {response_data.get('details')}"

[messages_logging]
missing_message = "No logging message found with section name {section_name}, message name {message_name}, \
and parameters {parameters} in logging toml files."

[config_loader]
no_config_file = "Failed to connect to toml config file at {config_file_path}. Ensure that you have created \
a config.toml file from the provided config_template.toml."
missing_config_data = "No toml_config_data found in toml_config_loader when get_config was called."
